language: ruby
notifications:
  email: false
rvm:
  - 2.1.5
install:
  - bundle install
cache: bundler
before_script:
  - psql -c 'create database almet_test;' -U postgres
  - cp config/database_example.yml config/database.yml
script:
  - bundle exec rake test
  - bundle exec rubocop -R
